// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUxVzIr_RUSTJ1FHY0KFHHnSFsmnuP74',
    appId: '1:874750484624:web:36af32824d8cbe6fcfb815',
    messagingSenderId: '874750484624',
    projectId: 'ceylonsphere-firebase',
    authDomain: 'ceylonsphere-firebase.firebaseapp.com',
    storageBucket: 'ceylonsphere-firebase.firebasestorage.app',
    measurementId: 'G-3LXTYJH99G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxnVUN5u4Ug1t9E5pnpPIufqChL6wJt4M',
    appId: '1:874750484624:android:d19bddbda6a30073cfb815',
    messagingSenderId: '874750484624',
    projectId: 'ceylonsphere-firebase',
    storageBucket: 'ceylonsphere-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjgBzhVM6Eviuu0ACtesjHbR8hfA-4E7o',
    appId: '1:874750484624:ios:c2c9ac1b9cba805bcfb815',
    messagingSenderId: '874750484624',
    projectId: 'ceylonsphere-firebase',
    storageBucket: 'ceylonsphere-firebase.firebasestorage.app',
    iosBundleId: 'com.chami.ceylonsphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjgBzhVM6Eviuu0ACtesjHbR8hfA-4E7o',
    appId: '1:874750484624:ios:93e2df8220b6fa13cfb815',
    messagingSenderId: '874750484624',
    projectId: 'ceylonsphere-firebase',
    storageBucket: 'ceylonsphere-firebase.firebasestorage.app',
    iosBundleId: 'com.example.gggg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkUxVzIr_RUSTJ1FHY0KFHHnSFsmnuP74',
    appId: '1:874750484624:web:d06ecffad96a4d58cfb815',
    messagingSenderId: '874750484624',
    projectId: 'ceylonsphere-firebase',
    authDomain: 'ceylonsphere-firebase.firebaseapp.com',
    storageBucket: 'ceylonsphere-firebase.firebasestorage.app',
    measurementId: 'G-08EJBKDSKR',
  );
}
