name: ceylonsphere
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.10.1
  geolocator: ^11.0.0
  google_places_flutter: ^2.1.0
  http: ^0.13.6
  permission_handler: ^11.3.0
  flutter_polyline_points: ^1.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.0.20
  model_viewer_plus: ^1.9.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  dash_chat_2: ^0.0.21
  image_picker: ^1.0.4
  flutter_gemini: ^2.0.1
  flutter_stripe: ^11.4.0
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.4
  google_fonts: ^4.0.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0 
  cloud_functions: ^5.3.4 
  firebase_storage: ^12.4.4
  google_sign_in: ^6.3.0
  sign_button: ^2.0.6
  audioplayers: ^5.2.1
  just_audio: ^0.9.34




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/ambuluwawa.webp
    - assets/ambuluwawa_gallery1.jpg
    - assets/ambuluwawa_gallery2.jpg
    - assets/ambuluwawa_gallery3.jpg
    - assets/ambuluwawa_gallery4.webp
    - assets/bamunu_mask.jpg
    - assets/bamunu_mask_01.glb
    - assets/bathik_sarong_for_women.webp
    - assets/bathik_sarong_for_women1.glb
    - assets/bathik_shirt_and_sarong.webp
    - assets/bathik_shirt_and_sarong1.glb
    - assets/buddha.jpg
    - assets/buddha1.glb
    - assets/elephant_sculpture.jpg
    - assets/elephant_sculpture1.glb
    - assets/galle_fort.jpg
    - assets/galle_fort_gallery1.jpg
    - assets/galle_fort_gallery2.jpeg
    - assets/galle_fort_gallery3.jpg
    - assets/galle_fort_gallery4.webp
    - assets/galle_fort_gallery5.jpg
    - assets/galle_fort_gallery6.jpg
    - assets/kandy1.jpg
    - assets/naga_rassa_mask.jpg
    - assets/naga_rassa_mask_01.glb
    - assets/nine_arch_bridge.webp
    - assets/nine_arch_gallery1.jpg
    - assets/nine_arch_gallery2.jpg
    - assets/nine_arch_gallery3.jpg
    - assets/nine_arch_gallery4.jpg
    - assets/nine_arch_gallery5.jpg
    - assets/nine_arch_gallery6.webp
    - assets/ruwanwelisaya.jpg
    - assets/ruwanwelisaya_gallery1.jpg
    - assets/ruwanwelisaya_gallery2.JPG
    - assets/ruwanwelisaya_gallery3.jpg
    - assets/ruwanwelisaya_gallery4.jpg
    - assets/ruwanwelisaya_gallery5.jpg
    - assets/sigiriya_gallery1.jpg
    - assets/sigiriya_gallery2.jpg
    - assets/sigiriya_gallery3.jpg
    - assets/sigiriya_gallery4.jpg
    - assets/sigiriya_gallery5.jpg
    - assets/sitting_man.webp
    - assets/sitting_man1.glb
    - assets/stupa.jpg
    - assets/stupa1.glb
    - assets/temple_gallery1.jpg
    - assets/temple_gallery2.jpg
    - assets/temple_gallery3.jpg
    - assets/temple_gallery4.jpg
    - assets/audio/AmbuluwawaAudioClip.mp3
    - assets/audio/GalleFortAudioClip.mp3
    - assets/audio/NineArchBridgeAudioClip.mp3
    - assets/audio/RuwanwelisayaAudioClip.mp3
    - assets/audio/SigiriyaAudioClip.mp3
    - assets/audio/TempleOfTheToothAudioClip.mp3
#    - assets/facebook-logo.png
#    - assets/firstscreen.jpg
#    - assets/google-logo.png
#    - assets/logo.png
#    - assets/Logo-10.png
#    - assets/Logo-12.png
#    - assets/logo-14.png
#    - assets/toyota-corolla.jpg
#    - assets/Honda-Civic.jpeg
#    - assets/Suzuki-Swift.jpg
#    - assets/robotglb.glb
#    - assets/app_island.glb


  uses-material-design: true

flutter_native_splash:
  color: "#42a5f5"
  background_image: "assets/beach.png"
  android: true
  ios: true
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill