name: CeylonSphere
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_maps_flutter: ^2.10.1
  geolocator: ^11.0.0
  http: ^0.13.6
  permission_handler: ^10.0.0
  flutter_polyline_points: ^1.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.0.20
  model_viewer_plus: ^1.9.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  camera: ^0.10.5+9





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/bamunu_mask_01.glb
    - assets/naga_rassa_mask_01.glb
#    - assets/facebook-logo.png
#    - assets/firstscreen.jpg
#    - assets/google-logo.png
#    - assets/logo.png
#    - assets/Logo-10.png
#    - assets/Logo-12.png
#    - assets/logo-14.png
#    - assets/toyota-corolla.jpg
#    - assets/Honda-Civic.jpeg
#    - assets/Suzuki-Swift.jpg
#    - assets/robotglb.glb
#    - assets/app_island.glb
#    - assets/bamunu_mask_01.glb



  uses-material-design: true