name: CeylonSphere
description: A Flutter chat application using Google's Gemini API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  speech_to_text: ^6.6.1
  flutter_tts: ^3.8.5
  image_picker: ^1.0.7
  dash_chat_2: ^0.0.20
  http: ^1.2.0
  flutter_markdown: ^0.6.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

