name: nearby_services_page
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1   # For beautiful fonts
  provider: ^6.1.2      # State management (optional)
  flutter_svg: ^2.0.10   # If you need SVG icons
  google_maps_flutter: ^2.10.0
  geolocator: ^10.1.0
  http: ^1.3.0         # Updated to the latest version
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
